name: Parallel and dependent demo

on:
  workflow_dispatch:

jobs:

  job-1:
    name: Independent job 1
    runs-on: ubuntu-latest
    steps:
      - name: Run job 1
        run: |
          echo "Job 1 running"
          sleep 5

  job-2:
    name: Independent job 2
    runs-on: ubuntu-latest970
    steps:
      - name: Run job 2
        run: |
          echo "Job 2 running"
          sleep 5

  job-3:
    name: Independent job 3
    runs-on: ubuntu-latest
    steps:
      - name: Run job 3
        run: |
          echo "Job 3 running"
          sleep 5

  job-4:
    name: Dependent job (depends on job 2)
    runs-on: ubuntu-latest
    needs: job-2
    steps:
      - name: Run dependent job
        run: |
          echo "Job 4 started after job 2 finished"
